### ISSUE TITLE
Project 1 - Task Checklist

### ISSUE THREAD

**Issue by aspanue** [GSPanue/mdx-grade-classifier#1]
**Task 1:** For each class below, design and implement (with jUnit) the following tests.
- Class Grade:
  - [x] TWO tests for inputs below and above the valid range for the constructor.
  - [x] ONE test for a valid input, checking that getPoints returns the right value.
  - [x] FIVE tests for classify, using Classifications as equivalence classes.
  - [x] TWO tests for inputs below and above the valid range for fromPercentage.
  - [x] TWENTY tests for fromPercentage, using each point in the 20-point scale as
an equivalence class.

- Class Profile:
  - [x] THREE tests for the constructor, one for each distinct way input can be invalid.
  - [x] SIX tests, one for each possible combination of Classification and truth
value (whether the profile is clear or not) as an equivalence class.

- Class Degree:
  - [x] THREE tests for the constructor, one for each distinct way input can be invalid.
  - [x] FIVE tests, using Classifications as equivalence classes.

**Task 2:** Implement the functionality required to pass the tests, with requirements as described
in Section 3.
- Class Grade:
  - [x] Complete

- Class Profile:
  - [x] Complete

- Class Degree: 
  - [x] Complete

**Task 3:** Achieve maximum branch coverage.
- Class Grade:
  - [x] Complete

- Class Profile:
  - [x] Complete

- Class Degree:
  - [x] Complete
